image: docker:stable

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - docker info

test:
  stage: test
  script:
    - docker run --name mysql -td
      -e MYSQL_RANDOM_ROOT_PASSWORD="yes"
      -e MYSQL_DATABASE="bitrix"
      -e MYSQL_USER="user"
      -e MYSQL_PASSWORD="password"
      mysql:5.7
    - docker run --name bitrix -td
      --link mysql -v $(pwd):/app/
      -e WEB_DOCUMENT_ROOT="/app/bitrix/"
      -e php.short_open_tag=1
      -e php.mbstring.func_overload=2
      -e php.display_errors=1
      webdevops/php-dev:5.6
    - cd bitrix
    - wget -q -O bitrix.zip $BITRIX_ZIP_URL
    - unzip bitrix.zip
    - wget -q -O dump.sql $BITRIX_SQL_URL
    - docker exec -i mysql mysql -uuser -ppassword < dump.sql
    - cd ..
    - docker exec -i -w /app/ bitrix composer install -n --prefer-dist
    - docker exec -i -w /app/ bitrix vendor/bin/phpunit --colors=never --coverage-text --whitelist src/