language: php

php:
  - "5.6"
  - "7.0"
  - "7.1"
  - "7.2"
  - "7.3"

services:
  - mysql

env:
  global:
    - MYSQL_HOST=127.0.0.1
    - MYSQL_DATABASE=bitrix
    - MYSQL_USER=root
    - MYSQL_PASSWORD=

before_install:
  - mysql -e 'CREATE DATABASE bitrix;'

install:
  - composer install --no-interaction
  - composer require --dev codacy/coverage

before_script:
  - echo 'short_open_tag = 1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'mbstring.func_overload = 2' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
  - php vendor/bin/phpunit --whitelist src/ --coverage-text --coverage-clover=coverage.xml

after_script:
  - php vendor/bin/codacycoverage clover coverage.xml
