language: php

php:
  - "5.6"

services:
  - mysql

env:
  - MYSQL_HOST=127.0.0.1
  - MYSQL_DATABASE=bitrix
  - MYSQL_USER=root
  - MYSQL_PASSWORD=


before_install:
  - mysql -e 'CREATE DATABASE bitrix;'

install:
  - composer install

script:
  - phpunit --whitelist src/ --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
