version: "3"
services:
  bitrix:
    image: webdevops/php-nginx-dev:5.6
    ports:
      - 80:80
    volumes:
      - ./:/app/
    environment:
      WEB_DOCUMENT_ROOT: /app/bitrix/
      WEB_DOCUMENT_INDEX: index.php
      php.short_open_tag: 1
      php.mbstring.func_overload: 2
      php.display_errors: 1
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: bitrix
      MYSQL_USER: user
      MYSQL_PASSWORD: password
