version: "3"
services:
  bitrix:
    image: webdevops/php-nginx-dev:5.6
    ports:
      - 80:80
    volumes:
      - ./:/app/
    environment:
      WEB_DOCUMENT_ROOT: /app/bitrix/
      WEB_DOCUMENT_INDEX: index.php
      php.short_open_tag: 1
      php.mbstring.func_overload: 2
      php.display_errors: 1
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
